DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS channels CASCADE;
DROP TABLE IF EXISTS statuses CASCADE;
DROP TABLE IF EXISTS clients_statuses CASCADE;
DROP TABLE IF EXISTS updates CASCADE;

CREATE TABLE channels (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE statuses (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL CHECK (position('@' IN email) > 1),
  password TEXT NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  role TEXT NOT NULL,
  reset TEXT
);

CREATE TABLE clients (
  id SERIAL PRIMARY KEY,
  first_name TEXT NOT NULL DEFAULT '',
  last_name TEXT NOT NULL DEFAULT '',
  gender TEXT NOT NULL DEFAULT 'Male',
  marital TEXT NOT NULL DEFAULT 'Unknown',
  contact TEXT NOT NULL DEFAULT '',
  relationship TEXT NOT NULL DEFAULT '',
  initial_contact_date DATE NOT NULL DEFAULT CURRENT_DATE,
  dob DATE NOT NULL DEFAULT '1900-01-01',
  email TEXT NOT NULL DEFAULT 'placeholder@fake.com',
  phone TEXT NOT NULL DEFAULT '000-000-0000',
  address TEXT NOT NULL DEFAULT '',
  citizenship TEXT NOT NULL DEFAULT 'Unknown',
  medicaid TEXT NOT NULL DEFAULT 'Unknown',
  daycare TEXT NOT NULL DEFAULT 'Unknown',
  physician TEXT NOT NULL DEFAULT '',
  diagnosis TEXT NOT NULL DEFAULT '',
  from_channel INTEGER NOT NULL DEFAULT 1
    REFERENCES channels ON DELETE CASCADE,
  current_status INTEGER NOT NULL DEFAULT 1
    REFERENCES statuses ON DELETE CASCADE,
  is_enrolled BOOLEAN NOT NULL DEFAULT FALSE,
  notes TEXT NOT NULL DEFAULT '',
  created_at DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE clients_statuses (
  id SERIAL PRIMARY KEY,
  client_id INTEGER NOT NULL
    REFERENCES clients ON DELETE CASCADE,
  status_id INTEGER NOT NULL
    REFERENCES statuses ON DELETE CASCADE,
  update_date DATE NOT NULL
);

CREATE TABLE updates (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL
    REFERENCES users ON DELETE SET NULL,
  client_id INTEGER  NOT NULL
    REFERENCES clients ON DELETE CASCADE,
  comment TEXT NOT NULL,
  commented_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);